### ISSUE TITLE
allow VerifyTestMain to check for leaks even when the tests fail

### ISSUE THREAD

**Issue by machine424** [uber-go/goleak#128]
Currently it only does that when they pass
https://github.com/uber-go/goleak/blob/898a938bf0d0ad15bb1619b0dfb0a1e3cbe73e33/testmain.go#L63-L66

Running the check in case of failure would help with debugging the failure.
Also, one may want to avoid leaks even when tests fail and `VerifyNone` ensures that e.g.

Are there any reasons or limitations for not running the check in all cases?

Omitting that condition seems to work as I expect it on some of my failing tests.

**Comment by machine424** [comment]
Hello! Thanks for taking a look at this.

> Interesting. Are there examples of cases where leaking goroutines causes the test failure?

Actually, I wasn’t thinking about tests failing because of the leaks, but I believe that having as much information as possible when a test fails can only be beneficial for debugging the test and the code being tested.

For example (really simplified one):

```
package main

import (
	"testing"
	"time"

	"go.uber.org/goleak"
)

func foo() {
    go func() {
        for {
            time.Sleep(1 * time.Second)
        }
    }()
}

func TestFoo(t *testing.T) {
	defer goleak.VerifyNone(t)

    foo()
    t.Fatal()
}
```

helps discover that `foo` will require some eyes. 

> This may be slightly tricky since it's difficult to determine if the leaking goroutine is from a goroutine spawned for purely testing purpose or if it's a goroutine spawned due to the thing you're testing.

As long as we print what each goroutine was doing, I personally don’t have a problem with that. Also, we may have such `false positive` leaks even when the package tests pass, but we still look for them.

**Comment by sywhang** [comment]
that's fair, i don't mind adding this as an Option so that this can be completed. Let me put up a PR on that shortly.
