### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jhuliano** [uber-go/goleak#33]
Is there any plan to create a new tag fallowing the semantic versioning? This since the latest tag (`v0.10.0`) was almost 2 years ago, which `go get` will use unless a commit is specified.
I see there is a V1 PR already merged (https://github.com/uber-go/goleak/pull/27), but if V1 it's still not stable/ready, would it be possible to tag the bug fix for t.Paralell (https://github.com/uber-go/goleak/pull/25) under something like `v0.10.1` or `v0.11.0`?

**Comment by prashantv** [comment]
Sorry for the delay, released a 1.0.
