### ISSUE TITLE
time.Tick leak not detected

### ISSUE THREAD

**Issue by komuw** [uber-go/goleak#44]
`time.Tick`[1] is documented as having a leak;
```
be aware that without a way to shut it down the underlying 
Ticker cannot be recovered by the garbage collector; it "leaks"
```     

I expected `go.uber.org/goleak` to be able to uncover such a leak but it didn't seem to. 

Here's my example program:
1. `main.go`
```go
package main

import (
	"fmt"
	"time"
)

func hello() string {
	t := time.Tick(3 * time.Second)      //leak
	final := time.Tick(10 * time.Second) //another leak

	for {
		select {
		case <-t:
			fmt.Println("ticked")
		case <-final:
			fmt.Println("FINAL ticked")
			return "final hello"
		default:
			fmt.Println("NOT ticked")
			time.Sleep(1 * time.Second)
		}
	}
}
```

2. `main_test.go`
```go
package main

import (
	"testing"
	"go.uber.org/goleak"
)

func TestHello(t *testing.T) {
	defer goleak.VerifyNone(t)
	res := hello()
	t.Log(res)
}
```

then I run tests as;   
`go test -v -race -count=1 ./...` 

ref:     
1. https://pkg.go.dev/time?tab=doc#Tick    
2. go version
go version go1.13.1 darwin/amd64

**Comment by prashantv** [comment]
`time.Tick` does not start a background goroutine, but registers an internal timer to write to the specified channel, hence it's not detected.

goleak is a goroutine leak detector, and while most leaks often also leak a goroutine, not all leaks do, and those leaks cannot be detected by goleak.

Closing this as there's no way for goleak to detect leaked timers as far as I can tell.
