### ISSUE TITLE
Goleak detects leaked goroutines from other tests

### ISSUE THREAD

**Issue by denis-tingaikin** [uber-go/goleak#48]
## Description

We've found an interesting thing during using goleak on our CI, that goleak can detect leaked goroutine from other tests.

## Steps to reproduce

1. Use go1.14.1 darwin/amd64
2. Use goleak v1.0.0 
3. Run test file below
`goleak_test.go`
```
package goleak_test

import (
	"go.uber.org/goleak"
	"testing"
	"time"
)

func TestA(t *testing.T) {
	go func() {
		for {
			<-time.After(time.Millisecond * 100)
		}
	}()
}

func TestB(t *testing.T) {
	defer goleak.VerifyNone(t)
}
```

**Expected:** TestB should pass 
**Actual:** TestB fails with error "found unexpected goroutines:"

**Comment by prashantv** [comment]
Yes, this is expected, as goleak cannot determine which test specifically is responsible for a leak, it just identifies that there is a leak when `VerifyNone` is run. If you had the same `defer goleak.VerifyNone(t)` in `TestAt`, it would detect that test as leaking too.

You could run the leak detection at the beginning and end of a test to ensure there were none before the test is started,
```go
func TestB(t *testing.T) {
	goleak.VerifyNone(t) // ensure there's no leaks before the test starts
	defer goleak.VerifyNone(t)
}
```

You could write your own helper for this as well.

**Comment by denis-tingajkin** [comment]
@prashantv thanks for the clarifications, I also got a question, can we add some option for goleak to ignore set of stacks. For example 

```go
func IngoreStacks(stacks ...stack.Stack) Option {
	stacksMap := map[int]bool{}
	for _, s := range stacks {
		stacksMap[s.ID] = true
	}
	return addFilter(func(s stack.Stack) bool {
		return stacksMap[s],
	})
}
```

And with this option I could use the next options for the example above:

```
defer goleak.VerifyNone(t, goleak.IngoreStacks(stack.All()...)
```

What do you think about this approach? :)
