### ISSUE TITLE
Running tests with `-trace` is failing for new versions of go

### ISSUE THREAD

**Issue by kapillamba4** [uber-go/goleak#66]
**Problem:**
Using goleak with trace flag in earlier versions of go (go1.13.10) is working fine due to fixed issue #39.

But in recent version of go (go1.17.1) testing simple programs with `trace flag` is failing again. I think the stack trace has now hidden the call to `runtime.goparkunlock`
```
func Test(t *testing.T) {
	defer goleak.VerifyNone(t)
}
```

```
make test:
        [Goroutine 18 in state trace reader (blocked), with runtime.ReadTrace on top of the stack:
        goroutine 18 [trace reader (blocked)]:
        runtime.ReadTrace()
        	/usr/local/go/src/runtime/trace.go:412 +0xd2
        runtime/trace.Start.func1()
        	/usr/local/go/src/runtime/trace/trace.go:129 +0x47
        created by runtime/trace.Start
        	/usr/local/go/src/runtime/trace/trace.go:127 +0xf4
```

**Possible Solution:**
Removing this piece of code:
https://github.com/uber-go/goleak/blob/1e9de543a7aac025a9cd43ec3805a432ea33600d/options.go#L159-L161

**Comment by kapillamba4** [comment]
cc @prashantv

**Comment by abhinav** [comment]
Thanks for reporting @kapillamba4. We'll look into this.

Internal ref: GO-887
