### ISSUE TITLE
Please drop unmaintained golang.org/x/lint dependency from go.mod

### ISSUE THREAD

**Issue by liggitt** [uber-go/goleak#92]
The golang.org/x/lint library is marked as deprecated / unmaintained / readonly

This library takes an explicit dependency on it in https://github.com/uber-go/goleak/blob/master/tools_test.go in order to record a specific version of it in go.mod, for use with `go install` in the `make lint` target.

The same result could be achieved by installing the same version explicitly in `make lint` with `go install golang.org/x/lint/golint@v0.0.0-20190930215403-16217165b5de`, and the tools_test.go and go.mod reference could be dropped, to avoid propagating an unmaintained dependency into downstreams that use this library.

**Comment by pohly** [comment]
Or even better, use golangci-lint. See https://github.com/uber-go/goleak/pull/95.
